'use client';
import { ArrowLeft, MoreVertical, Search, Upload } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import type { HotelDepartment, IncidentalCharge } from '@/lib/hotel-masters';

const blank = (): IncidentalCharge => ({ id: crypto.randomUUID(), title: '', amount: 0, taxScheme: 'SST-3', outletCode: '', rateElement: false, guestAppFb: false, guestAppOnlineShop: false, posInterface: false, eventInterface: false, allowNegative: true, packageRedemption: false, kiosk: false, thirdPartyPos: false, eInvoice: true, msicCode: '55101', classification: '022' });
const flags: Array<[keyof IncidentalCharge, string]> = [['rateElement', 'Rate Element'], ['guestAppFb', 'GuestApp - F&B'], ['guestAppOnlineShop', 'GuestApp - OnlineShop'], ['posInterface', 'POS Interface'], ['eventInterface', 'Event Interface'], ['allowNegative', 'Allow Negative'], ['packageRedemption', 'Package Redemption'], ['kiosk', 'Kiosk'], ['thirdPartyPos', '3rd Party POS'], ['eInvoice', 'e-Invoice']];

export function DepartmentModule({ departments, onChange, onBack }: { departments: HotelDepartment[]; onChange: (v: HotelDepartment[]) => void | Promise<void>; onBack: () => void }) {
  const [draft, setDraft] = useState(departments), [menu, setMenu] = useState<string | null>(null), [dept, setDept] = useState<string | null>(null), [charge, setCharge] = useState<IncidentalCharge | null>(null), [chargeList, setChargeList] = useState(false), [chargeMenu, setChargeMenu] = useState<string | null>(null), [saving, setSaving] = useState(false), [query, setQuery] = useState(''), [searchOpen, setSearchOpen] = useState(false);
  useEffect(() => setDraft(departments), [departments]);
  const department = draft.find((x) => x.id === dept);
  const visible = useMemo(() => draft.filter((d) => d.name.toLowerCase().includes(query.toLowerCase())), [draft, query]);
  const open = (d: HotelDepartment, c?: IncidentalCharge) => { setDept(d.id); setCharge(c ? { ...c } : blank()); setChargeList(false); setMenu(null); setChargeMenu(null); };
  const showCharges = (d: HotelDepartment) => { setDept(d.id); setCharge(null); setChargeList(true); setMenu(null); };
  const close = () => { setCharge(null); setChargeList(false); setDept(null); };
  const save = async () => { if (!department || !charge) return; const next = draft.map((d) => d.id !== department.id ? d : { ...d, incidentalCharges: d.incidentalCharges.some((c) => c.id === charge.id) ? d.incidentalCharges.map((c) => c.id === charge.id ? charge : c) : [...d.incidentalCharges, charge] }); setSaving(true); try { await onChange(next); setDraft(next); close(); } finally { setSaving(false); } };
  if (department && chargeList) return <section className="master-page incidental-list-page"><div className="department-editor-head"><button className="master-back" onClick={close}><ArrowLeft size={18} /> Back</button><strong>Incidental Charges</strong></div><div className="master-list-head incidental-list-head"><h1>Incidental Charges Listing <em>({department.incidentalCharges.length})</em></h1><Search size={21} /></div><div className="incidental-list">{department.incidentalCharges.map((item) => <article className="incidental-row" key={item.id}><div className="incidental-thumb" /><div className="incidental-copy"><strong>{item.title}</strong><small>MYR {Number(item.amount).toFixed(2)}</small></div><button className="department-menu-trigger" onClick={() => setChargeMenu(chargeMenu === item.id ? null : item.id)}><MoreVertical size={21} /></button>{chargeMenu === item.id && <div className="department-menu incidental-row-menu"><button onClick={() => open(department, item)}>Edit</button><button>QR Code</button></div>}</article>)}</div><button className="incidental-add-button" aria-label="Add incidental charge" onClick={() => open(department)}><span>+</span></button></section>;
  if (department && charge) return <section className="master-page incidental-charge-page"><div className="department-editor-head"><button className="master-back" onClick={close}><ArrowLeft size={18} /> Back</button><strong>Incidental Charges</strong></div><div className="master-detail-card incidental-charge-card"><div className="master-section-label">Charge Item</div><div className="master-form-grid"><label className="master-field master-field-wide"><span>Title</span><input value={charge.title} onChange={(e) => setCharge({ ...charge, title: e.target.value })} /></label><label className="master-field"><span>Amount (MYR)</span><input type="number" min="0" value={charge.amount} onChange={(e) => setCharge({ ...charge, amount: Number(e.target.value) })} /></label><label className="master-field"><span>Tax Scheme *</span><select value={charge.taxScheme} onChange={(e) => setCharge({ ...charge, taxScheme: e.target.value })}><option>SST-3</option><option>SST-4</option><option>SST-6</option><option>None</option></select></label><label className="master-field master-field-wide"><span>Outlet Code</span><input value={charge.outletCode} onChange={(e) => setCharge({ ...charge, outletCode: e.target.value })} /></label></div><div className="incidental-checks">{flags.map(([key, label]) => <label key={String(key)}><input type="checkbox" checked={Boolean(charge[key])} onChange={(e) => setCharge({ ...charge, [key]: e.target.checked })} />{label}</label>)}</div><div className="incidental-attachment"><span>Upload Attachment(s)</span><Upload size={18} /></div></div><div className="master-page-actions"><button className="secondary-button" onClick={close}>Cancel</button><button className="primary-button" disabled={!charge.title.trim() || saving} onClick={save}>{saving ? 'Saving…' : 'Save'}</button></div></section>;
  return <section className="master-page department-page"><div className="master-list-head department-list-head"><div><h1>Department <em>({draft.length})</em></h1></div><button className="department-search-button" aria-label="Search departments" onClick={() => setSearchOpen(!searchOpen)}><Search size={21} /></button></div>{searchOpen && <div className="department-search-field"><Search size={16} /><input autoFocus placeholder="Search department" value={query} onChange={(e) => setQuery(e.target.value)} /></div>}<div className="department-list">{visible.map((d) => <article className="department-row" key={d.id}><div><strong>{d.name}</strong><small>Incidental Charges : <b>{d.incidentalCharges.length}</b> | Reason : <b>{d.reasons.length}</b> | Sales Channel : <b>{d.salesChannels.length}</b></small></div><button className="department-menu-trigger" onClick={() => setMenu(menu === d.id ? null : d.id)}><MoreVertical size={21} /></button>{menu === d.id && <div className="department-menu"><button onClick={() => open(d)}>Edit</button><button onClick={() => showCharges(d)}>Incidental Charges</button><button>Reason</button><button>Sales Channel</button><button>Inactive</button></div>}</article>)}</div><button className="secondary-button master-page-back" onClick={onBack}><ArrowLeft size={16} /> Back to Hotel Settings</button></section>;
}
