'use client';

import { ArrowLeft, MoreVertical, Plus, Trash2, X } from 'lucide-react';
import { useEffect, useState } from 'react';
import type { HotelDepartment } from '@/lib/hotel-masters';

type DepartmentArea = 'edit' | 'incidentalCharges' | 'reasons' | 'salesChannels';
const labels: Record<Exclude<DepartmentArea, 'edit'>, string> = { incidentalCharges: 'Incidental Charges', reasons: 'Reason', salesChannels: 'Sales Channel' };

export function DepartmentModule({ departments, onChange, onBack }: { departments: HotelDepartment[]; onChange: (value: HotelDepartment[]) => void | Promise<void>; onBack: () => void }) {
  const [draft, setDraft] = useState(departments); const [active, setActive] = useState<string | null>(null); const [area, setArea] = useState<DepartmentArea | null>(null); const [menu, setMenu] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  useEffect(() => setDraft(departments), [departments]);
  const selected = draft.find((item) => item.id === active) ?? null;
  const update = (changed: HotelDepartment) => setDraft((items) => items.map((item) => item.id === changed.id ? changed : item));
  async function save() { setSaving(true); try { await onChange(draft); setArea(null); setActive(null); } finally { setSaving(false); } }
  function open(id: string, next: DepartmentArea) { setActive(id); setArea(next); setMenu(null); }
  function addDepartment() { const id = `department-${crypto.randomUUID().slice(0, 8)}`; setDraft((items) => [...items, { id, name: 'New Department', incidentalCharges: [], reasons: [], salesChannels: [] }]); setActive(id); setArea('edit'); }
  if (selected && area) {
    const listArea = area !== 'edit' ? area : null;
    const values = listArea ? selected[listArea] : [];
    return <section className="master-page department-page" aria-label="Department"><div className="department-editor-head"><button className="master-back" type="button" onClick={() => { setActive(null); setArea(null); }}><ArrowLeft size={18} /> Back</button><strong>{selected.name}</strong></div><div className="master-detail-card department-editor"><label className="master-field"><span>{area === 'edit' ? 'Department Name *' : labels[listArea!]}</span>{area === 'edit' ? <input autoFocus value={selected.name} onChange={(event) => update({ ...selected, name: event.target.value })} /> : <div className="department-entry-list">{values.map((value, index) => <div className="department-entry" key={`${value}-${index}`}><input value={value} onChange={(event) => update({ ...selected, [listArea!]: values.map((item, position) => position === index ? event.target.value : item) })} /><button type="button" aria-label={`Remove ${value}`} onClick={() => update({ ...selected, [listArea!]: values.filter((_, position) => position !== index) })}><Trash2 size={16} /></button></div>)}<button className="secondary-button department-add-entry" type="button" onClick={() => update({ ...selected, [listArea!]: [...values, `New ${labels[listArea!]}`] })}><Plus size={16} /> Add {labels[listArea!]}</button></div>}</label></div><div className="master-page-actions"><button className="secondary-button" type="button" onClick={() => { setActive(null); setArea(null); }}><X size={16} /> Cancel</button><button className="primary-button" type="button" onClick={save} disabled={!selected.name.trim() || saving}>{saving ? 'Saving…' : 'Save'}</button></div></section>;
  }
  return <section className="master-page department-page" aria-label="Department"><div className="master-list-head"><div><h1>Department <em>({draft.length})</em></h1><p>Hotel Department Setup.</p></div><button className="primary-button" type="button" onClick={addDepartment}><Plus size={18} /> Add</button></div><div className="department-list">{draft.map((department) => <article className="department-row" key={department.id}><div><strong>{department.name}</strong><small>{department.incidentalCharges.length > 0 && <>Incidental Charges : <b>{department.incidentalCharges.length}</b></>}{department.reasons.length > 0 && <>{department.incidentalCharges.length > 0 && ' | '}Reason : <b>{department.reasons.length}</b></>}{department.salesChannels.length > 0 && <>{(department.incidentalCharges.length > 0 || department.reasons.length > 0) && ' | '}Sales Channel : <b>{department.salesChannels.length}</b></>}</small></div><button className="department-menu-trigger" type="button" aria-label={`Actions for ${department.name}`} onClick={() => setMenu(menu === department.id ? null : department.id)}><MoreVertical size={21} /></button>{menu === department.id && <div className="department-menu"><button onClick={() => open(department.id, 'edit')}>Edit</button><button onClick={() => open(department.id, 'incidentalCharges')}>Incidental Charges</button><button onClick={() => open(department.id, 'reasons')}>Reason</button><button onClick={() => open(department.id, 'salesChannels')}>Sales Channel</button></div>}</article>)}</div><button className="secondary-button master-page-back" type="button" onClick={onBack}><ArrowLeft size={16} /> Back to Hotel Settings</button></section>;
}
