'use client';

import { MoreVertical, UserRound } from 'lucide-react';
import { useState } from 'react';
import type { GuestProfile } from '@/lib/transport-state';

const blank = (): GuestProfile => ({ id: crypto.randomUUID(), name: '', mobile: '', email: '', nationality: 'Malaysian', identityNo: '', address: '', country: 'Malaysia', state: '', city: '', postcode: '', birthDate: '', occupation: '', accountName: '', guestType: 'Normal', adultChild: 'Adult', remark: '', newsletter: false, tourismTax: false, visits: 0, updated: new Date().toISOString().slice(0, 10) });

export function GuestProfiles({ profiles, onSave, onBack }: { profiles: GuestProfile[]; onSave: (value: GuestProfile[]) => Promise<void>; onBack: () => void }) {
  const [editing, setEditing] = useState<GuestProfile | null>(null);
  const save = async () => { if (!editing?.name.trim()) return; await onSave([editing, ...profiles.filter(item => item.id !== editing.id)]); setEditing(null); };
  if (editing) return <section className="guest-profile-page"><div className="guest-profile-banner"><button onClick={() => setEditing(null)}>‹</button><strong>Guest Profile</strong></div><div className="guest-profile-card"><h2>Guest Information</h2><div className="guest-profile-grid">{([['name','Guest Name *'],['mobile','Mobile No. (Optional)'],['email','Email Address *'],['nationality','Nationality *'],['identityNo','IC No / Passport No *'],['address','Address'],['country','Country *'],['state','State *'],['city','City'],['postcode','Postcode'],['birthDate','Birth Date'],['occupation','Occupation'],['accountName','Account Name (If applicable)'],['guestType','Guest Type *'],['remark','Remark']] as const).map(([key,label]) => <label key={key}><span>{label}</span><input value={editing[key]} onChange={event => setEditing({ ...editing, [key]: event.target.value })} /></label>)}<label><span>Adult/Child *</span><select value={editing.adultChild || 'Adult'} onChange={event => setEditing({ ...editing, adultChild: event.target.value as 'Adult' | 'Child' })}><option>Adult</option><option>Child</option></select></label><label className="guest-toggle"><span>News Letter</span><input type="checkbox" checked={editing.newsletter} onChange={event => setEditing({ ...editing, newsletter: event.target.checked })} /></label><label className="guest-toggle"><span>Tourism Tax</span><input type="checkbox" checked={editing.tourismTax} onChange={event => setEditing({ ...editing, tourismTax: event.target.checked })} /></label></div></div><div className="guest-profile-actions"><button onClick={() => setEditing(null)}>Cancel</button><button className="primary-button" onClick={save}>Save</button></div></section>;
  return <section className="guest-profile-page"><div className="guest-profile-banner"><strong>Guest Profile</strong></div><div className="guest-profile-list-head"><strong>Guests (<em>{profiles.length}</em>)</strong><button onClick={() => setEditing(blank())}>＋</button></div><div className="guest-profile-list">{profiles.map(profile => <button className="guest-profile-row" key={profile.id} onClick={() => setEditing(profile)}><UserRound size={15}/><strong>{profile.name}</strong><span>{profile.email}</span><small>No. Of Visit: <b>{profile.visits}</b></small><time>{profile.mobile}<br/>{profile.updated}</time><MoreVertical size={18}/></button>)}</div></section>;
}
