'use client';
import { ArrowLeft } from 'lucide-react';
import { useEffect, useState } from 'react';
import type { RoomStatus } from '@/lib/hotel-masters';
export function RoomStatusModule({ statuses, onChange, onBack }: { statuses: RoomStatus[]; onChange: (value: RoomStatus[]) => void | Promise<void>; onBack: () => void }) {
  const [draft, setDraft] = useState(statuses); const [saving, setSaving] = useState(false);
  useEffect(() => setDraft(statuses), [statuses]); const changed = JSON.stringify(draft) !== JSON.stringify(statuses);
  async function save() { setSaving(true); try { await onChange(draft); } finally { setSaving(false); } }
  return <section className="master-page room-status-page" aria-label="Room Status"><div className="master-list-head"><div><h1>Room Status</h1><p>Room Status Setup.</p></div></div><div className="master-detail-card room-status-card"><div className="room-status-grid room-status-header"><span>Room Status</span><span>Status Code</span><span>Status Color</span><span>Active</span></div>{draft.map((status) => <div className="room-status-grid room-status-row" key={status.code}><strong>{status.description}</strong><span className="room-status-code">{status.code}</span><label className="room-status-color"><input type="color" value={status.color} aria-label={`Change ${status.description} colour`} onChange={(event) => setDraft((items) => items.map((item) => item.code === status.code ? { ...item, color: event.target.value } : item))} /></label><label className="room-status-toggle"><input type="checkbox" checked={status.active} onChange={(event) => setDraft((items) => items.map((item) => item.code === status.code ? { ...item, active: event.target.checked } : item))} /><span /></label></div>)}</div><div className="master-page-actions"><button className="secondary-button" type="button" onClick={onBack}><ArrowLeft size={16} /> Back to Hotel Settings</button><button className="primary-button" type="button" disabled={!changed || saving} onClick={save}>{saving ? 'Saving…' : 'Save'}</button></div></section>;
}
