'use client';
import { MoreVertical, Plus, Search } from 'lucide-react';
import { useEffect, useState } from 'react';
import { initialSegments, type HotelSegment } from '@/lib/hotel-masters';
export function SegmentModule({ segments, onChange, onBack }: { segments: HotelSegment[]; onChange: (value: HotelSegment[]) => Promise<void>; onBack: () => void }) {
 const source = segments.length ? segments : initialSegments; const [draft,setDraft]=useState(source),[menu,setMenu]=useState<string|null>(null),[editing,setEditing]=useState<HotelSegment|null>(null),[dialogOpen,setDialogOpen]=useState(false),[description,setDescription]=useState(''),[sequence,setSequence]=useState(1); useEffect(()=>setDraft(segments.length ? segments : initialSegments),[segments]);
 const open=(item?:HotelSegment)=>{setMenu(null);setEditing(item||null);setDialogOpen(true);setDescription(item?.description||'');setSequence(item?.displaySequence||draft.length+1)};
 const save=async()=>{if(!description.trim())return;const value=editing?draft.map(x=>x.id===editing.id?{...x,description:description.trim(),displaySequence:sequence,updatedAt:new Date().toISOString().slice(0,10)}:x):[...draft,{id:crypto.randomUUID(),description:description.trim(),displaySequence:sequence,icon:'',active:true,updatedAt:new Date().toISOString().slice(0,10)}];await onChange(value);setDraft(value);setDialogOpen(false);setEditing(null)};
 return <section className="master-page segment-page"><div className="master-list-head"><h1>Segments <em>({draft.length})</em></h1><Search size={21}/></div><div className="segment-list">{draft.map(item=><article className="segment-row" key={item.id}><div><strong>{item.description}</strong><small>Last posted on {item.updatedAt}</small></div><button onClick={()=>setMenu(menu===item.id?null:item.id)} aria-label="Segment options"><MoreVertical size={21}/></button>{menu===item.id&&<div className="segment-menu"><button onClick={()=>open(item)}>Edit</button><button onClick={async()=>{const value=draft.map(x=>x.id===item.id?{...x,active:false}:x);await onChange(value);setDraft(value);setMenu(null)}}>Inactive</button></div>}</article>)}</div><button className="segment-add" onClick={()=>open()}><Plus size={24}/></button><button className="secondary-button master-page-back" onClick={onBack}>Back to Hotel Settings</button>{editing!==null||description===''&&false?null:null}{editing!==null && <div className="billing-instruction-overlay"><div className="billing-instruction-card segment-dialog"><h2>{editing ? 'Edit Segment' : 'Add Segment'}</h2><label>Description *<input value={description} onChange={e=>setDescription(e.target.value)}/></label><label>Display Sequence<input type="number" min="1" value={sequence} onChange={e=>setSequence(Number(e.target.value))}/></label><div className="billing-instruction-actions"><button className="secondary-button" onClick={()=>{setDialogOpen(false);setEditing(null)}}>Cancel</button><button className="primary-button" disabled={!description.trim()} onClick={save}>Save</button></div></div></div>}</section>;
}




