import assert from 'node:assert/strict';
import { build } from 'esbuild';
const result = await build({ entryPoints: ['lib/transport-state.ts'], bundle: true, platform: 'node', format: 'esm', write: false });
const { newTransportState, applyTransportAction } = await import('data:text/javascript;base64,' + Buffer.from(result.outputFiles[0].text).toString('base64'));
let state = newTransportState();
const master = state.hotelMasters.roomTypes.find(room => room.active && room.maxGuest >= 2);
const booking = { reference: 'ROOMTEST', guest: 'Test Booker', arrival: '2026-09-10', departure: '2026-09-11', status: 'Booked', rooms: [{ code: master.code, count: 1, adults: 1, children: 0 }], guests: 1, assignedRooms: 0, checkedInGuests: 0, amount: 100 };
state = applyTransportAction(state, { type: 'bookingCreate', value: booking });
assert.equal(state.guestProfiles.length, 1);
assert.equal(state.guestProfiles[0].name, 'Test Booker');
assert.deepEqual(state.bookings[0].rooms[0].guestProfileIds, [state.guestProfiles[0].id]);
state = applyTransportAction(state, { type: 'bookingUpdate', value: { ...state.bookings[0], guests: 2, rooms: [{ ...state.bookings[0].rooms[0], adults: 2 }] } });
assert.equal(state.bookings[0].rooms[0].adults, 2);
assert.deepEqual(state.bookings[0].rooms[0].guestProfileIds, [state.guestProfiles[0].id]);
state = applyTransportAction(state, { type: 'guestProfilesSave', value: [{ ...state.guestProfiles[0], name: 'Updated Guest', paymentRemark1: 'Deposit paid' }] });
assert.equal(state.guestProfiles.find(p => p.id === state.bookings[0].rooms[0].guestProfileIds[0]).name, 'Updated Guest');
const count = state.guestProfiles.length;
state = applyTransportAction(state, { type: 'roomingEnsure', reference: 'ROOMTEST' });
assert.equal(state.guestProfiles.length, count);
console.log('Rooming checks passed: automatic booker profile, retained profile links, manual pax update, shared guest edits, idempotent initialization.');
